language: java
script: mvn clean site

deploy: # Publish static Doxygen html files to gh-pages branch, accessible at https://<username>.github.io/PSMoveSteamVRBridge
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: target/site
  on:
    branch: master
